# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gulshan/sem4/Graphics/Pacman-Killer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gulshan/sem4/Graphics/Pacman-Killer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gulshan/sem4/Graphics/Pacman-Killer/CMakeFiles /home/gulshan/sem4/Graphics/Pacman-Killer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gulshan/sem4/Graphics/Pacman-Killer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pacman-killer

# Build rule for target.
pacman-killer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pacman-killer
.PHONY : pacman-killer

# fast build rule for target.
pacman-killer/fast:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/build
.PHONY : pacman-killer/fast

src/ball.o: src/ball.cpp.o

.PHONY : src/ball.o

# target to build an object file
src/ball.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/ball.cpp.o
.PHONY : src/ball.cpp.o

src/ball.i: src/ball.cpp.i

.PHONY : src/ball.i

# target to preprocess a source file
src/ball.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/ball.cpp.i
.PHONY : src/ball.cpp.i

src/ball.s: src/ball.cpp.s

.PHONY : src/ball.s

# target to generate assembly for a file
src/ball.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/ball.cpp.s
.PHONY : src/ball.cpp.s

src/color.o: src/color.cpp.o

.PHONY : src/color.o

# target to build an object file
src/color.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/color.cpp.o
.PHONY : src/color.cpp.o

src/color.i: src/color.cpp.i

.PHONY : src/color.i

# target to preprocess a source file
src/color.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/color.cpp.i
.PHONY : src/color.cpp.i

src/color.s: src/color.cpp.s

.PHONY : src/color.s

# target to generate assembly for a file
src/color.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/color.cpp.s
.PHONY : src/color.cpp.s

src/ground.o: src/ground.cpp.o

.PHONY : src/ground.o

# target to build an object file
src/ground.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/ground.cpp.o
.PHONY : src/ground.cpp.o

src/ground.i: src/ground.cpp.i

.PHONY : src/ground.i

# target to preprocess a source file
src/ground.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/ground.cpp.i
.PHONY : src/ground.cpp.i

src/ground.s: src/ground.cpp.s

.PHONY : src/ground.s

# target to generate assembly for a file
src/ground.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/ground.cpp.s
.PHONY : src/ground.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/magnet.o: src/magnet.cpp.o

.PHONY : src/magnet.o

# target to build an object file
src/magnet.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/magnet.cpp.o
.PHONY : src/magnet.cpp.o

src/magnet.i: src/magnet.cpp.i

.PHONY : src/magnet.i

# target to preprocess a source file
src/magnet.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/magnet.cpp.i
.PHONY : src/magnet.cpp.i

src/magnet.s: src/magnet.cpp.s

.PHONY : src/magnet.s

# target to generate assembly for a file
src/magnet.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/magnet.cpp.s
.PHONY : src/magnet.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nonedit.o: src/nonedit.cpp.o

.PHONY : src/nonedit.o

# target to build an object file
src/nonedit.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/nonedit.cpp.o
.PHONY : src/nonedit.cpp.o

src/nonedit.i: src/nonedit.cpp.i

.PHONY : src/nonedit.i

# target to preprocess a source file
src/nonedit.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/nonedit.cpp.i
.PHONY : src/nonedit.cpp.i

src/nonedit.s: src/nonedit.cpp.s

.PHONY : src/nonedit.s

# target to generate assembly for a file
src/nonedit.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/nonedit.cpp.s
.PHONY : src/nonedit.cpp.s

src/other_handlers.o: src/other_handlers.cpp.o

.PHONY : src/other_handlers.o

# target to build an object file
src/other_handlers.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/other_handlers.cpp.o
.PHONY : src/other_handlers.cpp.o

src/other_handlers.i: src/other_handlers.cpp.i

.PHONY : src/other_handlers.i

# target to preprocess a source file
src/other_handlers.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/other_handlers.cpp.i
.PHONY : src/other_handlers.cpp.i

src/other_handlers.s: src/other_handlers.cpp.s

.PHONY : src/other_handlers.s

# target to generate assembly for a file
src/other_handlers.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/other_handlers.cpp.s
.PHONY : src/other_handlers.cpp.s

src/packman.o: src/packman.cpp.o

.PHONY : src/packman.o

# target to build an object file
src/packman.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/packman.cpp.o
.PHONY : src/packman.cpp.o

src/packman.i: src/packman.cpp.i

.PHONY : src/packman.i

# target to preprocess a source file
src/packman.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/packman.cpp.i
.PHONY : src/packman.cpp.i

src/packman.s: src/packman.cpp.s

.PHONY : src/packman.s

# target to generate assembly for a file
src/packman.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/packman.cpp.s
.PHONY : src/packman.cpp.s

src/plank.o: src/plank.cpp.o

.PHONY : src/plank.o

# target to build an object file
src/plank.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/plank.cpp.o
.PHONY : src/plank.cpp.o

src/plank.i: src/plank.cpp.i

.PHONY : src/plank.i

# target to preprocess a source file
src/plank.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/plank.cpp.i
.PHONY : src/plank.cpp.i

src/plank.s: src/plank.cpp.s

.PHONY : src/plank.s

# target to generate assembly for a file
src/plank.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/plank.cpp.s
.PHONY : src/plank.cpp.s

src/pond.o: src/pond.cpp.o

.PHONY : src/pond.o

# target to build an object file
src/pond.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/pond.cpp.o
.PHONY : src/pond.cpp.o

src/pond.i: src/pond.cpp.i

.PHONY : src/pond.i

# target to preprocess a source file
src/pond.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/pond.cpp.i
.PHONY : src/pond.cpp.i

src/pond.s: src/pond.cpp.s

.PHONY : src/pond.s

# target to generate assembly for a file
src/pond.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/pond.cpp.s
.PHONY : src/pond.cpp.s

src/porcupine.o: src/porcupine.cpp.o

.PHONY : src/porcupine.o

# target to build an object file
src/porcupine.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/porcupine.cpp.o
.PHONY : src/porcupine.cpp.o

src/porcupine.i: src/porcupine.cpp.i

.PHONY : src/porcupine.i

# target to preprocess a source file
src/porcupine.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/porcupine.cpp.i
.PHONY : src/porcupine.cpp.i

src/porcupine.s: src/porcupine.cpp.s

.PHONY : src/porcupine.s

# target to generate assembly for a file
src/porcupine.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/porcupine.cpp.s
.PHONY : src/porcupine.cpp.s

src/timer.o: src/timer.cpp.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/tree.o: src/tree.cpp.o

.PHONY : src/tree.o

# target to build an object file
src/tree.cpp.o:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/tree.cpp.o
.PHONY : src/tree.cpp.o

src/tree.i: src/tree.cpp.i

.PHONY : src/tree.i

# target to preprocess a source file
src/tree.cpp.i:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/tree.cpp.i
.PHONY : src/tree.cpp.i

src/tree.s: src/tree.cpp.s

.PHONY : src/tree.s

# target to generate assembly for a file
src/tree.cpp.s:
	$(MAKE) -f CMakeFiles/pacman-killer.dir/build.make CMakeFiles/pacman-killer.dir/src/tree.cpp.s
.PHONY : src/tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pacman-killer"
	@echo "... src/ball.o"
	@echo "... src/ball.i"
	@echo "... src/ball.s"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/ground.o"
	@echo "... src/ground.i"
	@echo "... src/ground.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/magnet.o"
	@echo "... src/magnet.i"
	@echo "... src/magnet.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nonedit.o"
	@echo "... src/nonedit.i"
	@echo "... src/nonedit.s"
	@echo "... src/other_handlers.o"
	@echo "... src/other_handlers.i"
	@echo "... src/other_handlers.s"
	@echo "... src/packman.o"
	@echo "... src/packman.i"
	@echo "... src/packman.s"
	@echo "... src/plank.o"
	@echo "... src/plank.i"
	@echo "... src/plank.s"
	@echo "... src/pond.o"
	@echo "... src/pond.i"
	@echo "... src/pond.s"
	@echo "... src/porcupine.o"
	@echo "... src/porcupine.i"
	@echo "... src/porcupine.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/tree.o"
	@echo "... src/tree.i"
	@echo "... src/tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

